//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por AVANCE PIA.rc
//
#define DLG_MOD_ENVIO                   9
#define DLG_INICIO_SESION               101
#define DLG_REGISTRO                    103
#define IDR_MENU1                       107
#define DLG_INF_VENDEDOR                108
#define DLG_ALTA_PRODUCTOS              110
#define DLG_ENVIOS                      112
#define DLG_NUEVO_ENVIO                 114
#define DLG_RESUMEN_ENVIOS              118
#define DLG_PRODUCTOS                   122
#define DLG_MOD_PRODUCTO                124
#define DLG_INFO_VENDEDOR               128
#define DLG_INF_VENDEDOR_EDIT           130
#define TXT_MOD_CALLE                   1003
#define TXT_MOD_COLONIA_ENVIO           1004
#define TXT_MOD_CIUDAD_ENVIO            1007
#define TXT_MOD_MENSAJE_ENVIO           1008
#define TXT_MOD_MARCA_PROD              1009
#define TXT_DESC_PROD                   1010
#define LBX_PRODUCTOS                   1011
#define LBL_MOD_PROD_ENVIO              1015
#define CMB_MOD_ESTADO_ENVIO            1016
#define IDC_DATETIMEPICKER1             1017
#define LBL_MOD_CANT_ENVIO              1018
#define TXT_USUARIO                     1022
#define TXT_CONTRASENA                  1023
#define BTN_INICIAR_SESION              1024
#define BTN_REGISTRAR_USUARIO           1025
#define TXT_NEW_USUARIO                 1026
#define TXT_CONTRASENA_REGISTRAR        1027
#define BTN_AGREGAR_USUARIO             1028
#define TXT_NOMBRE_USUARIO              1029
#define TXT_EMPRESA                     1030
#define BTN_SUBIR_IMAGEN                1031
#define BTN_CONFIRMAR_INFO_VENDEDOR     1032
#define BTN_ALTA_PROD                   1033
#define BTN_BAJA_PROD                   1034
#define BTN_MOD_PROD                    1035
#define TXT_NOMBRE_PROD                 1036
#define TXT_CANT_PROD                   1037
#define TXT_CODE_PROD                   1038
#define TXT_MARCA_PROD                  1039
#define BTN_CONFIRM_PROD                1040
#define BTN_MASOP_PROD                  1041
#define BTN_CANCELARPROD                1041
#define TXT_MOD_NOM_PROD                1042
#define TXT_MOD_CANT_PROD               1043
#define TXT_MOD_CODE_PROD               1044
#define TXT_MOD_DESC_PROD               1045
#define BTN_ACEPTAR_MOD_PROD            1046
#define BTN_CANCELAR_MOD_PROD           1047
#define BTN_RESUM_ENVIOS                1048
#define BTN_MOD_ENVIOS                  1049
#define BTN_ELIMINAR_ENVIOS             1050
#define BTN_NUEVO_ENVIOS                1051
#define LBL_SELEC_PROD                  1052
#define TXT_CALLE                       1053
#define TXT_COLONIA                     1054
#define TXT_CIUDAD                      1055
#define LBL_ESTADO                      1056
#define TXT_MENSAJE_ENVIO               1057
#define LBL_CANT_PROD                   1058
#define BTN_ACEPTAR_ENVIO               1059
#define BTN_CANCELAR_ENVIO              1060
#define BTN_ACEPTAR_RESUM_ENVIO         1061
#define BTN_ACEPTAR_MOD_ENVIO           1062
#define BTN_CANCELAR_MOD_ENVIO          1063
#define TXT_PRECIO_PROD                 1064
#define TXT_MOD_PRECIO_PROD             1065
#define LBX_ENVIOS                      1066
#define BTN_CANCELAR_ENREGISTRO         1069
#define TXT_REGISTRAR_USUARIO           1070
#define PB_USUARIO                      1071
#define BTN_EDIT_INFO_VENDEDOR          1072
#define PB_VENDEDOR                     1075
#define LBL_VENDEDORSTATIC              1076
#define LBL_EMPRESASTATIC               1077
#define TXT_NOMBRE_EDIT_INFO            1078
#define TXT_EMPRESA_EDIT_INFO           1079
#define BTN_CONFIRMAR_EDICION_INFO      1081
#define BTN_CARGAR_IMAGEN_EDIT_INFO     1082
#define BTN_SALIR_INICIO_SESION         1083
#define BTN_SALIR_REGISTRO              1083
#define PB_EDIT_IMAGEN_INFO             1084
#define BTN_IMAGEN1PROD                 1085
#define BTN_IMAGEN2PROD                 1086
#define PB_IMAGEN1PROD                  1087
#define PB_IMAGEN2PROD                  1088
#define BTN_MOD_IMAGEN1_PROD            1090
#define BTN_MOD_IMAGEN2_PROD            1092
#define PB_MOD_IMAGEN1_PROD             1093
#define PB_MOD_IMAGEN2_PROD             1094
#define BTN_MOSTRARENVIO                1095
#define BTN_EDITARENVIOS                1096
#define PB_IMAGEN1PRODUC                1097
#define PB_IMAGEN2PRODUC                1098
#define LBL_CALLESTATIC                 1100
#define LBL_COLONIASTATIC               1101
#define LBL_CIUDADSTATIC                1102
#define LBL_MENSAJESTATIC               1103
#define LBL_CANTIDADSTATIC              1104
#define TXT_CANTIDADMOD                 1105
#define TXT_CANTIDAD                    1105
#define LBL_TOTALENVIO                  1107
#define BTN_ASIGNARTOTAL                1108
#define LBL_PRODUCTOSTATIC              1109
#define LBL_ESTADOSTATIC                1110
#define LBL_FECHASTATIC                 1111
#define LBL_TOTALSTATIC                 1112
#define LBL_MODTOTAL                    1113
#define BTN_CALCULARTOTALMOD            1114
#define LBL_NOMBREENALTA                1116
#define PB_FOTOENALTA                   1117
#define PB_FOTOENVIOS                   1118
#define LBL_NOMBREENVIOS                1119
#define PB_FOTOMODENVIO                 1120
#define LBL_NOMBREMODENVIO              1121
#define PB_FOTOMODPROD                  1122
#define LBL_NOMBREMODPROD               1123
#define PB_FOTONUEVOENVIO               1124
#define LBL_NOMBRENUEVOENVIO            1125
#define PB_FOTOPRODUCTOSS               1126
#define LBL_NOMBREPRODUCTOSS            1127
#define IDC_SCROLLBAR1                  1128
#define PB_FOTORESUMENENVIO             1129
#define LBL_NOMBRERESUMENENVIO          1130
#define ID_INFO_VENDEDOR                40001
#define ID_SALIR                        40002
#define ID_ENVIOS_MOSTRARENVIOS         40007
#define ID_ALTA_PRODUCTOS               40009
#define ID_CAMBIO_PRODUCTOS             40010
#define ID_BAJA_PRODUCTOS               40012
#define ID_NUEVO_ENVIO                  40013
#define ID_ENVIOS_MODIFICARENVIO        40014
#define ID_ENVIOS_ELIMINARENVIO         40015

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         40017
#define _APS_NEXT_CONTROL_VALUE         1131
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
